name: wizarr

services:
  wizarr:
    image: ghcr.io/wizarrrr/wizarr:latest
    container_name: wizarr
    restart: unless-stopped
    labels:
      wud.watch: "true"
      wud.watch.digest: "true"
      wud.trigger.include: "docker.backupgated"
    environment:
      PUID: "1000"
      PGID: "1000"
      DISABLE_BUILTIN_AUTH: "false"
      TZ: "${TZ:-Europe/Amsterdam}"
    ports:
      - "192.168.0.112:5690:5690/tcp"
    volumes:
      - /srv/appdata/docker/wizarr:/data
