name: wud

services:
  wud:
    image: getwud/wud:latest
    container_name: wud
    restart: unless-stopped
    environment:
      TZ: "${TZ:-Europe/Amsterdam}"
      WUD_WATCHER_INFRA_SOCKET: /var/run/docker.sock
      WUD_WATCHER_INFRA_WATCHBYDEFAULT: "false"
      WUD_WATCHER_INFRA_CRON: "0 * * * *"
      WUD_WATCHER_APPS_HOST: 192.168.0.112
      WUD_WATCHER_APPS_PORT: "2376"
      WUD_WATCHER_APPS_CAFILE: /certs/ca.pem
      WUD_WATCHER_APPS_CERTFILE: /certs/client-cert.pem
      WUD_WATCHER_APPS_KEYFILE: /certs/client-key.pem
      WUD_WATCHER_APPS_WATCHBYDEFAULT: "false"
      WUD_WATCHER_APPS_CRON: "0 * * * *"
      WUD_WATCHER_SERVARR_HOST: 192.168.0.102
      WUD_WATCHER_SERVARR_PORT: "2376"
      WUD_WATCHER_SERVARR_CAFILE: /certs/ca.pem
      WUD_WATCHER_SERVARR_CERTFILE: /certs/client-cert.pem
      WUD_WATCHER_SERVARR_KEYFILE: /certs/client-key.pem
      WUD_WATCHER_SERVARR_WATCHBYDEFAULT: "false"
      WUD_WATCHER_SERVARR_CRON: "0 * * * *"
      WUD_TRIGGER_DOCKER_BACKUPGATED_AUTO: "false"
      WUD_TRIGGER_DOCKER_BACKUPGATED_INCLUDEBYDEFAULT: "false"
      WUD_TRIGGER_DOCKER_BACKUPGATED_PRUNE: "false"
    ports:
      - "127.0.0.1:3001:3000/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/appdata/docker/wud/store:/store
      - /etc/dothomelab/wud-docker-api:/certs:ro
    healthcheck:
      test:
        - CMD-SHELL
        - curl --fail http://127.0.0.1:3000/health || exit 1
      start_period: 20s
      timeout: 5s
      interval: 30s
      retries: 3
    labels:
      wud.watch: "false"
